  language: python
  python:
    - "3.6"
  install:
    - pip install pandas
    - pip install seaborn
    - pip install codecov
  script:
    - coverage run papillon/test/test*.py
  after_success:
    - codecov
