  language: python
  python:
    - "3.6"
  install:
    - pip install pandas
    - pip install seaborn
    - pip install codecov
    - pip install imagehash
  before_script:
    - cd test
  script:
    - coverage run test_papillon.py
  after_success:
    - codecov
